version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=zoTmGA51i8
      - MONGO_INITDB_DATABASE=shoppinglist
    ports:
      - '27017:27017'
    volumes:
      - /media/pwojtaszko/DATA_STORAGE/shoppingList/db:/data/db

  nestjs:
    build:
      context: ./backend # Path to the NestJS Dockerfile and source
      dockerfile: Dockerfile
    container_name: nestjs-container
    ports:
      - '3000:3000'
    volumes:
      - /path/to/your/nestjs-source:/usr/src/app # You can update this path
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_HOST=
      - MONGO_DB_PORT=
      - MONGO_DB_NAME=
      - MONGO_DB_USER=
      - MONGO_DB_PASSWORD=
      - JWT_SECRET=

  react:
    build:
      context: ./shopping-list # Path to the React Dockerfile and source
      dockerfile: Dockerfile
    container_name: react-container
    ports:
      - '3001:3001'
    environment:
      - API_HOST=
    volumes:
      - /path/to/your/react-build:/usr/share/nginx/html # You can update this path
