export enum CategoriesEnum {
  alcohols = "alcohols",
  medical = "medical",
  readyMeals = "readyMeals",
  petSupplies = "petSupplies",
  houseAndGarden = "houseAndGarden",
  babyProducts = "babyProducts",
  electronics = "electronics",
  hygiene = "hygiene",
  teaAndCoffee = "teaAndCoffee",
  cannedAndPreserved = "cannedAndPreserved",
  meatAndColdCuts = "meatAndColdCuts",
  frozen = "frozen",
  dairy = "dairy",
  fruitsAndVegetables = "fruitsAndVegetables",
  stationery = "stationery",
  bakery = "bakery",
  spicesSaucesOils = "spicesSaucesOils",
  fishAndSeafood = "fishAndSeafood",
  dryGoodsAndPasta = "dryGoodsAndPasta",
  sweets = "sweets",
  clothing = "clothing",
  vege = "vege",
  waterAndDrinks = "waterAndDrinks",
  cleaningSupplies = "cleaningSupplies",
  other = "other",
}

export enum UnitsEnum {
  [""] = "none",
  pcs = "piece",
  kg = "kilogram",
  l = "liter",
  ml = "milliliter",
  g = "gram ",
}
